import type { Metadata } from "next";
import PageShell from "@/app/components/PageShell";

export const metadata: Metadata = {
  title: "Terms of Use",
  description: "The terms that apply when you use CityMitra’s guides, directory, and AI planner.",
  alternates: { canonical: "/terms" }
};

const contactEmail = process.env.NEXT_PUBLIC_CONTACT_EMAIL || "helpdesk@ctmitra.com";

export default function TermsPage() {
  return (
    <PageShell>
      <article className="policyPage">
        <h1>Terms of Use</h1>
        <p>
          <i>Last updated: June 2026.</i> By using CityMitra you agree to these terms. If you do not agree, please do
          not use the service.
        </p>

        <h2>1. What CityMitra is</h2>
        <p>
          CityMitra provides city guides, a category directory, and an AI planning assistant for Indian cities. It is
          an information and planning tool — not a booking platform, not an emergency service, and not professional
          (medical, legal, or financial) advice.
        </p>

        <h2>2. Verify before you travel</h2>
        <p>
          Suggestions — including AI chat answers, curated picks, distances, and timings — are starting points.
          Opening hours, prices, road conditions, availability, and safety conditions change. Verify in live maps or
          by calling ahead before acting on anything, especially hospital, fuel, and high-altitude travel plans.
        </p>

        <h2>3. AI-generated content</h2>
        <p>
          Chat answers are generated by an AI model and may be incomplete or out of date. They are produced at your
          request, for your planning use. Do not rely on them as the sole basis for decisions involving health,
          safety, or significant money.
        </p>

        <h2>4. Acceptable use</h2>
        <ul>
          <li>No scraping, bulk querying, or attempting to overload the service or its AI endpoints.</li>
          <li>No attempting to access the admin area or other users’ data.</li>
          <li>No using the chat to generate unlawful, harmful, or deceptive content.</li>
        </ul>

        <h2>5. Listings and businesses</h2>
        <p>
          Curated picks are editorial selections, not endorsements or guarantees. If we introduce paid placements,
          they will be labelled. Businesses can request corrections or removal via the contact page.
        </p>

        <h2>6. Intellectual property</h2>
        <p>
          Guide text and site design are © CityMitra. City photos load from Wikipedia/Wikimedia Commons and Unsplash
          under their respective licences. You may share links and short quotes with attribution; do not republish
          guides wholesale.
        </p>

        <h2>7. Liability</h2>
        <p>
          The service is provided “as is”, without warranties. To the maximum extent permitted by law, CityMitra is
          not liable for losses arising from use of the service, including decisions made based on suggestions or AI
          answers. These terms are governed by the laws of India.
        </p>

        <h2>8. Contact</h2>
        <p>
          Questions about these terms: <a href={`mailto:${contactEmail}?subject=Terms`}>{contactEmail}</a>.
        </p>
      </article>
    </PageShell>
  );
}
